### ISSUE TITLE
MAP - Main Capital

### ISSUE THREAD

**Issue by Phoenix-Ra** [Grand-Theft-Warzone/GTW-World-Design#1]
Western Governorate In Progress

**Comment by A1phaa1** [comment]
![CAPITALWIP1](https://github.com/Grand-Theft-Warzone/GTW-World-Design/assets/91205946/c679f0a1-8db9-48e0-bd9c-87ec4ae632dd)
-orange is buildings above 15 floors or under

-light orange is buildings 10 floors or no more than 12

-yellow is buildings under 10 floors only

-green is the park

-light blue will be used for major projects

**Comment by A1phaa1** [comment]
![CAPITALWIP2](https://github.com/Grand-Theft-Warzone/GTW-World-Design/assets/91205946/c4e46555-976c-42fd-8bed-60cf4d0a20d3)
Current Progress:

**Comment by A1phaa1** [comment]
Downtown Main Buildings Completed.
only a few sub-buildings and lighting and detailing is remaining



![Image](https://github.com/Grand-Theft-Warzone/GTW-World-Design/assets/91205946/27140e79-adba-452b-a484-dc8c9076d668)
